Feature/002 resetting of encrypted shared preferences
neXenio/RxPreferences pull request #3
Opened 2021-10-21 19:09 UTC by marvinmirtschin

2021-10-22 08:38 UTC, Steppschuh requested changes

2021-10-22 08:38 UTC, Steppschuh commented on rxpreferences/src/main/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProvider.java
> +            file = new File(context.getApplicationInfo().dataDir + "/shared_prefs/" + SHARED_PREFERENCES_NAME + ".xml.bak");
Duplicated code, can be extracted to new method

2021-10-22 08:38 UTC, Steppschuh commented on rxpreferences/src/main/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProvider.java
> +                .andThen(Completable.fromAction(() -> sharedPreferences = createEncryptedSharedPreferences(context).blockingGet()));
Why the `.blockingGet()`? Can be part of the stream.

2021-10-22 08:38 UTC, Steppschuh commented on rxpreferences/src/main/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProvider.java
> +    public Completable deletePreferencesFile(@NonNull Context context) {
Is there any use case for deleting the file but keeping the preferences in memory? If not, move the clearing to this method.

2021-10-22 08:38 UTC, Steppschuh commented on app/src/androidTest/java/com/nexenio/rxpreferences/provider/TestableEncryptedSharedPreferencesProvider.java
> +    public Completable deletePreferencesFile(@NonNull Context context) {
Why the overwrite? Isn't this the same implementation?

2021-10-22 08:38 UTC, Steppschuh commented on app/src/androidTest/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProviderTest.java
> +    public void cleanUp() throws KeyStoreException {
Why before and after? If you want to clean up after all tests are done, you can use `@AfterClass` instead.

2021-10-22 08:38 UTC, Steppschuh commented on app/src/androidTest/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProviderTest.java
> +    // Comment notes: MasterKey available / preferencesFile available / in-memory preferences available
Hard to memorize, would prefer the full text on each test in JavaDoc comment `/**  ... */`

2021-10-22 08:38 UTC, Steppschuh commented on app/src/androidTest/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProviderTest.java
> +        Scanner myReader = new Scanner(validFile);
Rename to `scanner`

2021-10-22 08:38 UTC, Steppschuh commented on app/src/androidTest/java/com/nexenio/rxpreferences/provider/EncryptedSharedPreferencesProviderTest.java
> +                .remove("__androidx_security_crypto_encrypted_prefs_key_keyset__")
Are there constants available for these names? If not you could create them.

2021-10-22 08:38 UTC, Steppschuh commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava3:rxjava:3.1.0'
Adjust order to not mix `implementation`, `testImplementation` and `androidTestImplementation`

2021-10-25 13:05 UTC, devbeckmann commented
LGTM

2021-10-25 13:13 UTC, devbeckmann approved these changes

2021-10-25 13:25 UTC, merged